import UIKit

/**
	Types of `QRCode`s that can be generated by the API.
 */
public enum QRCodePaymentReferenceType: String {
	/** Associated to a Payment Request */
	case PAYMENT_REQUEST

	/** Associated to a `PaymentSession` */
	case PAYMENT_SESSION
}
